nodeLinker: pnp

npmAuthToken: 3566d6c9-6a0b-4de3-8567-8c81efd2cd48

packageExtensions:
  "@firebase/auth@*":
    dependencies:
      "@firebase/app-types": "*"
      "@firebase/util": "*"
  "@firebase/database@*":
    dependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@protobufjs/inquire@*":
    dependencies:
      long: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  firebase-admin@*:
    dependencies:
      "@firebase/app-types": "*"
    peerDependencies:
      "@firebase/app-types": "*"
  follow-redirects@*:
    dependencies:
      debug: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  puppeteer-extra-plugin-stealth@*:
    dependencies:
      puppeteer: "*"
      puppeteer-extra: "*"
  puppeteer-extra-plugin-user-data-dir@*:
    dependencies:
      puppeteer: "*"
      puppeteer-extra: "*"
  puppeteer-extra-plugin-user-preferences@*:
    dependencies:
      puppeteer: "*"
      puppeteer-extra: "*"
  puppeteer-extra@*:
    dependencies:
      puppeteer-extra-plugin-stealth: "*"
      puppeteer-extra-plugin-user-preferences: "*"
      puppeteer-extra-plugin-user-data-dir: "*"
  twilio@*:
    dependencies:
      "@types/express": "*"
      "@types/qs": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest"

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.4.1.cjs
