nodeLinker: pnp

yarnPath: .yarn/releases/yarn-2.4.0.cjs

npmAuthToken: 3566d6c9-6a0b-4de3-8567-8c81efd2cd48

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: "https://yarn.build/latest"

packageExtensions:
  "puppeteer-extra-plugin-stealth@*":
    dependencies:
      "puppeteer-extra": "*"
  "@firebase/auth@*":
    dependencies:
      "@firebase/app-types": "*"
      "@firebase/util": "*"
  "@firebase/database@*":
    dependencies:
      "@firebase/app-types": "*"
  "firebase-admin@*":
    dependencies:
        "@firebase/app-types": "*"
    peerDependencies:
      "@firebase/app-types": "*"
  "twilio@*":
    dependencies:
      "@types/qs": "*"
      "@types/express": "*"
  "puppeteer-extra@*":
    dependencies:
      "puppeteer-extra-plugin-stealth": "*"
  "functions@*":
    dependencies:
      "puppeteer-extra": "*"
      "puppeteer-extra-plugin-stealth": "*"

